### ISSUE TITLE
Veilguard Compatibility

### ISSUE THREAD

**Issue by Kepeerre** [IPdotSetAF/FrostyBulkExporter#3]
Hello, I was wondering if there's a way to make this work with Dragon Age Veilguard, Im mainly interested on textures. Thanks for the amazing work!

**Comment by adastmin1** [comment]
https://skrinshoter.ru/sSVURiU0m0V

https://skrinshoter.ru/sSVx9ETzmO5

But our hands are not hooks.

**Comment by IPdotSetAF** [comment]
@Ryugamox sorry for the late reply. github forgot to notify me :p 

 can you open the game in the frosty editor? if not you should ask for support in [https://github.com/CadeEvs/FrostyToolsuite](https://github.com/CadeEvs/FrostyToolsuite) first. when the support is added then notify me to update the repo to sync the supported games.

if the frosty editor already opens it, then the tool should probably work on **Dragon Age Veilguard** as well, but there might be bugs, if so send me the errors regarding the **BullkExporter plugin**.

**Comment by Kepeerre** [comment]
@IPdotSetAF Hey, thanks for the response. Yes, gibthub often fails to notify. The editor was not opening the game, but Im still playing so I'll try once I finish and let you know. Have a nice one!

**Comment by IPdotSetAF** [comment]
@Ryugamox  seems like there is a **Dragon Age** support in the Frosty editor, although I don't own the game to test run the Bulk exporter on it. so feel free to send me any errors you are facing with extracting game textures.
